import { Graph } from "graphology"
// Import the graphology-graphml module properly
import * as GraphML from "graphology-graphml"

class GraphService {
  createSampleGraph() {
    // Initialize a new undirected graph
    const graph = new Graph()

    // Add some nodes with attributes
    graph.addNode("A", { label: "Node A", x: 0, y: 0, size: 10, color: "#ff0000" })
    graph.addNode("B", { label: "Node B", x: 1, y: 1, size: 15, color: "#00ff00" })
    graph.addNode("C", { label: "Node C", x: 0, y: 2, size: 5, color: "#0000ff" })
    graph.addNode("D", { label: "Node D", x: 2, y: 0, size: 8, color: "#ffff00" })

    // Add edges between nodes
    graph.addEdge("A", "B", { weight: 1, label: "A-B connection" })
    graph.addEdge("B", "C", { weight: 2, label: "B-C connection" })
    graph.addEdge("C", "A", { weight: 3, label: "C-A connection" })
    graph.addEdge("D", "B", { weight: 4, label: "D-B connection" })

    return graph
  }

  exportToGraphML(graph) {
    try {
      // Check if graph is null or undefined first
      if (!graph) {
        return this._createErrorGraphML("No graph provided")
      }

      // Since GraphML.default only has parse but no write method,
      // we'll use our custom implementation directly without trying the library
      return this.createBasicGraphML(graph)
    } catch (error) {
      return this._createErrorGraphML(error.message)
    }
  }

  _createErrorGraphML(errorMessage) {
    return `<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns">
 <!-- Error: ${errorMessage} -->
 <graph id="G" edgedefault="undirected">
 </graph>
</graphml>`
  }

  // Create a basic GraphML format
  createBasicGraphML(graph) {
    // Check if graph is null or undefined
    if (!graph) {
      return this._createErrorGraphML("No graph provided")
    }

    let output = '<?xml version="1.0" encoding="UTF-8"?>\n'
    output += '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">\n'
    output += "  <!-- Generated by BizarreBird GraphML Exporter -->\n"

    // Attribute declarations
    output += '  <key id="label" for="node" attr.name="label" attr.type="string"/>\n'
    output += '  <key id="x" for="node" attr.name="x" attr.type="double"/>\n'
    output += '  <key id="y" for="node" attr.name="y" attr.type="double"/>\n'
    output += '  <key id="size" for="node" attr.name="size" attr.type="double"/>\n'
    output += '  <key id="color" for="node" attr.name="color" attr.type="string"/>\n'
    output += '  <key id="weight" for="edge" attr.name="weight" attr.type="double"/>\n'
    output += '  <key id="edgelabel" for="edge" attr.name="label" attr.type="string"/>\n'

    // Graph element
    output += '  <graph id="G" edgedefault="undirected">\n'

    // Nodes
    graph.forEachNode((nodeId, attrs) => {
      output += `    <node id="${nodeId}">\n`
      if (attrs.label) output += `      <data key="label">${attrs.label}</data>\n`
      if (attrs.x !== undefined) output += `      <data key="x">${attrs.x}</data>\n`
      if (attrs.y !== undefined) output += `      <data key="y">${attrs.y}</data>\n`
      if (attrs.size !== undefined) output += `      <data key="size">${attrs.size}</data>\n`
      if (attrs.color) output += `      <data key="color">${attrs.color}</data>\n`
      output += "    </node>\n"
    })

    // Edges
    graph.forEachEdge((edgeId, attrs, source, target) => {
      output += `    <edge id="${edgeId}" source="${source}" target="${target}">\n`
      if (attrs.weight !== undefined) output += `      <data key="weight">${attrs.weight}</data>\n`
      if (attrs.label) output += `      <data key="edgelabel">${attrs.label}</data>\n`
      output += "    </edge>\n"
    })

    // Close tags
    output += "  </graph>\n"
    output += "</graphml>"

    return output
  }

  importFromGraphML(graphmlString) {
    try {
      // Check if graphmlString is valid
      if (!graphmlString || typeof graphmlString !== "string") {
        return new Graph()
      }

      // Try to use GraphML.default.parse based on the library structure
      if (GraphML.default && typeof GraphML.default.parse === "function") {
        return GraphML.default.parse(Graph, graphmlString)
      } else if (typeof GraphML.parse === "function") {
        return GraphML.parse(Graph, graphmlString)
      } else {
        return new Graph()
      }
    } catch (error) {
      // In case of error, return an empty graph
      return new Graph()
    }
  }
}

export default GraphService
